name: Deploy static site to Azure Web App - webapp-demo-0723

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC478B6D2F844564A62AA6897598DDFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F559ECE6612E4F72951B18A38A9157DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8FAB9CA4EDB4AFE83277336B975EEB0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webapp-demo-0723'
          slot-name: 'Production'
          package: .
